// Merge guild.config.example.json with the optional guild.config.json into generated/guild.config.json.
// Both the browser bundle and the Worker import the generated file, so one config drives everything.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const merge = (base, extra) => {
  if (!extra || typeof extra !== 'object' || Array.isArray(extra)) return base;
  const out = { ...base };
  for (const [key, value] of Object.entries(extra)) {
    const current = out[key];
    out[key] = value && typeof value === 'object' && !Array.isArray(value) && current && typeof current === 'object' && !Array.isArray(current)
      ? merge(current, value) : value;
  }
  return out;
};

const example = JSON.parse(await readFile(`${root}guild.config.example.json`, 'utf8'));
let custom = {};
if (existsSync(`${root}guild.config.json`)) {
  try { custom = JSON.parse(await readFile(`${root}guild.config.json`, 'utf8')); }
  catch (error) { console.error(`guild.config.json is not valid JSON: ${error.message}`); process.exit(1); }
}
const resolved = merge(example, custom);
delete resolved.$schema;
const problems = [];
if (!/^[a-z]{2}$/.test(resolved.language || '')) problems.push('language must be a two-letter code (en, ja, ...)');
if (!Array.isArray(resolved.machines) || !resolved.machines.length || !resolved.machines.every(m => /^[a-z0-9-]{1,32}$/.test(m?.id || '') && typeof m.label === 'string')) problems.push('machines[] needs {id: ^[a-z0-9-]{1,32}$, label}');
if (typeof resolved.guild?.name !== 'string' || !resolved.guild.name.trim()) problems.push('guild.name is required');
if (problems.length) { console.error(problems.map(p => `config error: ${p}`).join('\n')); process.exit(1); }

await mkdir(`${root}generated`, { recursive: true });
await writeFile(`${root}generated/guild.config.json`, JSON.stringify(resolved, null, 2) + '\n');
// A JS module avoids JSON import-attribute differences between Node, Vite and wrangler.
await writeFile(`${root}generated/guild.config.js`, `// Generated by scripts/prepare-config.mjs — do not edit. Edit guild.config.json instead.\nexport default ${JSON.stringify(resolved, null, 2)};\n`);
await writeFile(`${root}generated/guild.config.d.ts`, `import type { GuildConfig } from '../src/types';\ndeclare const config: GuildConfig;\nexport default config;\n`);
console.log(`generated/guild.config.json: "${resolved.guild.name}" (${resolved.language}), ${resolved.machines.length} machine(s)${existsSync(`${root}guild.config.json`) ? '' : ' — using the example config; run the setup in SETUP.md to personalise'}`);
