import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Backpack, Check, ChevronLeft, ChevronRight, Clock3, Copy, Info, Laptop, Loader2, Monitor, Network, Orbit, RefreshCw, ShieldCheck, Sword, X } from 'lucide-react';
import type { Category, Inventory, Item, Machine } from './types';
import { useInventory, type SyncMeta } from './useInventory';
import { ago, agentPrompt, categories, categoryOf, date, ItemDetail, ItemRow, JobRow, machineName, matches, Modal, roleTitle, SearchField, shortName, strengths } from './ui';
import { CharacterPortrait, CharacterProvider, NewCharacters } from './characters';
import { PlayerStatus } from './PlayerStatus';
import './styles.css';
import { GameIcon, CategoryArtwork, DepthSurface } from './GameUI';
import './game-ui.css';
import { applyTheme, config, machines } from './config';
import { t, tl } from './i18n';
import { PlayerAvatar } from './game-art';

type Page = 'home' | 'library' | 'agents' | 'automations' | 'favorites' | 'sources' | 'map';
const guildName = config.guild?.name || 'AI Guild';
const playerName = config.player?.name || 'Player';
const navigation = [
  { id: 'home' as const, label: t('nav.home'), title: guildName, art: 'home' as const, sub: t('nav.home.sub') },
  { id: 'agents' as const, label: t('nav.agents'), title: t('nav.agents.title'), art: 'agents' as const, sub: t('nav.agents.sub') },
  { id: 'library' as const, label: t('nav.library'), title: t('nav.library.title'), art: 'collection' as const, sub: t('nav.library.sub') },
  { id: 'automations' as const, label: t('nav.automations'), title: t('nav.automations.title'), art: 'automation' as const, sub: t('nav.automations.sub') },
];
const pageFromHash = (): Page => { const p = location.hash.slice(1).split('?')[0]; return ['home', 'library', 'agents', 'automations', 'favorites', 'sources', 'map'].includes(p) ? p as Page : 'home'; };
function loadFavorites(): string[] { try { const v = JSON.parse(localStorage.getItem('ai-guild-favorites') || '[]'); return Array.isArray(v) ? v.filter(x => typeof x === 'string') : []; } catch { return []; } }
const featured = (config.agents?.featured || []).map(v => v.toLowerCase());

function App() {
  const { inventory, sync, error, loading, now, lastContact, stale, refresh } = useInventory();
  const [page, setPage] = useState<Page>(pageFromHash), [query, setQuery] = useState(''), [category, setCategory] = useState<Category | 'all'>('all');
  const [machine, setMachine] = useState('all'), [stateFilter, setStateFilter] = useState('all'), [jobKind, setJobKind] = useState('all'), [agentRuntime, setAgentRuntime] = useState('all');
  const [limit, setLimit] = useState(24), [selected, setSelected] = useState<Item | null>(null), [favorites, setFavorites] = useState(loadFavorites), [searchOpen, setSearchOpen] = useState(false), [toast, setToast] = useState(''), [sort, setSort] = useState('default');
  const [partnerId, setPartnerId] = useState('');
  const [executionFilter, setExecutionFilter] = useState('all');
  const items = inventory?.items || [], agents = items.filter(i => i.category === 'agent'), jobs = items.filter(i => i.category === 'automation');
  const selectionId = selected?.id, currentItem = items.find(i => i.id === selectionId) || selected;
  const counts = useMemo(() => Object.fromEntries(categories.map(c => [c.id, items.filter(i => i.category === c.id).length])) as Record<Category, number>, [items]);
  const partnerList = useMemo(() => {
    const picked = featured.map(n => agents.find(i => i.id.toLowerCase() === n || shortName(i).toLowerCase() === n)).filter((i): i is Item => !!i);
    return picked.length ? picked : agents.slice(0, 6);
  }, [agents]);
  const partner = agents.find(i => i.id === partnerId) || partnerList[0] || agents[0];
  const savedCount = items.filter(i => favorites.includes(i.id)).length;
  const runtimeKinds = useMemo(() => [...new Set(agents.flatMap(i => i.runtimes))].slice(0, 4), [agents]);
  const title = navigation.find(n => n.id === page)?.title || ({ favorites: t('nav.favorites.title'), sources: t('nav.sources'), map: t('nav.map') }[page as 'favorites' | 'sources' | 'map']);
  const syncLabel = error ? t('sync.reconnecting') : !sync ? t('sync.connecting') : stale ? t('sync.lastRecord') : t('sync.live');
  const reset = () => { setQuery(''); setCategory('all'); setMachine('all'); setStateFilter('all'); setAgentRuntime('all'); setJobKind('all'); setExecutionFilter('all'); setLimit(24); };
  function go(next: Page, cat: Category | 'all' = 'all') { setPage(next); location.hash = next; reset(); setCategory(cat); window.scrollTo({ top: 0, behavior: 'instant' }); }
  const openCategory = (cat: Category) => go(cat === 'agent' ? 'agents' : cat === 'automation' ? 'automations' : 'library', cat);
  function favorite(id: string) { setFavorites(old => { const next = old.includes(id) ? old.filter(i => i !== id) : [...old, id]; try { localStorage.setItem('ai-guild-favorites', JSON.stringify(next)); setToast(next.includes(id) ? t('toast.saved') : t('toast.removed')); } catch { setToast(t('toast.saveFailed')); } return next; }); }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setToast(t('toast.copied')); } catch { setToast(t('toast.copyFailed')); } }
  function cyclePartner(direction: number) { const n = partnerList.findIndex(i => i.id === partner?.id); setPartnerId(partnerList[(n + direction + partnerList.length) % partnerList.length]?.id || ''); }
  useEffect(() => { const onHash = () => { setPage(pageFromHash()); setSelected(null); }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => { const f = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); setSearchOpen(v => !v); } }; window.addEventListener('keydown', f); return () => window.removeEventListener('keydown', f); }, []);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3000); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => setLimit(24), [query, category, machine, stateFilter, jobKind, agentRuntime, executionFilter, page]);
  useEffect(() => { if (selectionId && inventory && !inventory.items.some(i => i.id === selectionId)) { setSelected(null); setToast(t('toast.itemGone')); } }, [inventory, selectionId]);
  const filtered = useMemo(() => {
    const rows = items.filter(i => (page !== 'favorites' || favorites.includes(i.id)) && (page !== 'agents' || i.category === 'agent') && (page !== 'automations' || i.category === 'automation') && (category === 'all' || i.category === category) && (machine === 'all' || i.machines.includes(machine)) && (stateFilter === 'all' || i.status === stateFilter) && (executionFilter === 'all' || (executionFilter === 'running' ? i.schedule?.running === true : i.schedule?.loaded === true && i.schedule?.running === false)) && (jobKind === 'all' || i.schedule?.kind === jobKind) && (agentRuntime === 'all' || i.runtimes.includes(agentRuntime)) && matches(i, query));
    if (sort === 'name') return [...rows].sort((a, b) => a.name.localeCompare(b.name, config.language));
    if (sort === 'attention' || page === 'automations' && sort === 'default') return [...rows].sort((a, b) => Number(b.status === 'attention') - Number(a.status === 'attention'));
    return rows;
  }, [items, page, favorites, category, machine, stateFilter, jobKind, agentRuntime, executionFilter, query, sort]);

  return <div className="app-shell">
    <a className="skip-link" href="#main-content">{t('skip')}</a>
    <aside className="sidebar">
      <button className="brand" onClick={() => go('home')} aria-label={t('brand.home', { guild: guildName })}><GameIcon name="guild" size={54} className="brand-mark"/><span>{guildName}<small>{config.guild?.tagline}</small></span></button>
      <div className="side-caption">{t('side.caption')}</div>
      <nav aria-label={t('nav.aria')}>{navigation.map(n => <button key={n.id} onClick={() => go(n.id)} className={`nav-item ${page === n.id ? 'active' : ''}`} aria-current={page === n.id ? 'page' : undefined}><GameIcon name={n.art} size={48}/><span>{n.label}<small>{n.sub}</small></span>{page === n.id && <span className="nav-active-dot"/>}</button>)}</nav>
      <div className="side-secondary"><button className={`nav-item ${page === 'favorites' ? 'active' : ''}`} onClick={() => go('favorites')}><GameIcon name="favorites" size={44}/><span>{t('nav.favorites')}<small>{t('nav.favorites.sub')}</small></span><b>{savedCount}</b></button><button className={`nav-item ${page === 'map' ? 'active' : ''}`} onClick={() => go('map')}><GameIcon name="map" size={44}/><span>{t('nav.map')}<small>{t('nav.map.sub')}</small></span></button></div>
      <div className="side-bottom"><button className={`nav-item ${page === 'sources' ? 'active' : ''}`} aria-current={page === 'sources' ? 'page' : undefined} onClick={() => go('sources')}><GameIcon name="sync" size={44}/><span>{t('nav.sources')}<small>{t('nav.sources.sub')}</small></span></button><div className="player-card"><PlayerMini/><span><small>{t('player.label')}</small><strong>{playerName}</strong></span><ShieldCheck size={17}/></div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><button className="mobile-brand" onClick={() => go('home')} aria-label={t('topbar.homeAria')}><GameIcon name="home" size={44}/></button><div className="breadcrumb"><span>{t('topbar.world')}</span><ChevronRight size={13}/><strong>{title}</strong></div><div className="top-actions"><button className={`sync-pill ${error || stale ? 'warning' : 'online'}`} onClick={() => go('sources')} aria-label={t('sync.statusAria', { label: syncLabel })}><span className="sync-dot"/>{syncLabel}</button><button className="icon-button" aria-label={t('search.allAria')} onClick={() => setSearchOpen(true)}><GameIcon name="search" size={36}/></button><button className="icon-button mobile-favorites" aria-label={t('favorites.openAria')} onClick={() => go('favorites')}><GameIcon name="favorites" size={34}/></button></div></header>
      <main id="main-content" className={`page-${page}`} tabIndex={-1}>
        {(error || stale) && inventory && <div className="connection-warning" role="status"><Info size={20}/><div><strong>{error ? t('warn.reconnecting') : t('warn.stale')}</strong><p>{error || t('warn.delayed')} {t('warn.lastReceived', { ago: ago(sync?.receivedAt, now) })}</p></div><button className="icon-button" onClick={() => void refresh()} aria-label={t('refresh.aria')}><RefreshCw size={20}/></button></div>}
        {!inventory ? <section className="loading-state"><div className="loading-orb">{loading ? <Loader2 className="spin" size={35}/> : <Orbit size={35}/>}</div><span className="eyebrow">{t('loading.eyebrow')}</span><h1>{loading ? t('loading.title') : t('loading.waiting')}</h1><p>{error || t('loading.body')}</p><button className="primary" onClick={() => void refresh()}>{t('loading.retry')}<RefreshCw size={18}/></button></section> : <>
          {page === 'home' && <>
            <PlayerStatus agents={agents.length} items={items.length}/>
            <DeviceStatus inventory={inventory} now={now} onOpen={() => go('sources')}/>
            <div className="guild-home-grid">
              <section className="partner-section"><SectionTitle title={t('home.partner.title')} eyebrow={t('home.partner.eyebrow')} action={t('home.partner.action')} onAction={() => go('agents')}/>{partner && <div className="partner-panel"><DepthSurface className="partner-stage"><CharacterPortrait item={partner} size={220} className="spotlight-avatar"/><span className="partner-runtime">{(partner.runtimes[0] || '').toUpperCase()}</span><div className="stage-controls"><button className="icon-button" onClick={() => cyclePartner(-1)} aria-label={t('home.partner.prev')}><ChevronLeft size={20}/></button><button className="icon-button" onClick={() => cyclePartner(1)} aria-label={t('home.partner.next')}><ChevronRight size={20}/></button></div></DepthSurface><div className="partner-info" key={partner.id}><span className="partner-class">{roleTitle(partner)}</span><h3>{shortName(partner)}</h3><p>{strengths(partner).slice(0, 2).join(' · ') || partner.summary}</p><button className="text-button" onClick={() => setSelected(partner)}>{t('home.partner.details')}<ArrowRight size={17}/></button></div><div className="partner-picker" aria-label={t('home.partner.pickerAria')}>{partnerList.map(i => <button key={i.id} className={i.id === partner.id ? 'chosen' : ''} aria-pressed={i.id === partner.id} aria-label={t('home.partner.pick', { name: shortName(i) })} onClick={() => setPartnerId(i.id)}><CharacterPortrait item={i} size={56}/><span>{shortName(i)}</span></button>)}</div></div>}</section>
              <section className="equipment-section"><SectionTitle title={t('home.equipment.title')} eyebrow={t('home.equipment.eyebrow')} action={t('home.equipment.action')} onAction={() => go('library')}/><div className="equipment-shelves">{categories.filter(c => !['agent', 'automation'].includes(c.id)).map((c, index) => <button key={c.id} className={`shelf ${c.color}`} onClick={() => openCategory(c.id)}><span className="shelf-number">0{index + 1}</span><CategoryArtwork category={c.id}/><span><strong>{c.label}</strong><small>{c.description}</small></span><b>{counts[c.id]}<small>{t('home.equipment.unit')}</small></b><ChevronRight size={17}/></button>)}</div></section>
            </div>
            <NewCharacters items={items} onOpen={setSelected}/>
            <section className="quest-preview"><GameIcon name="automation" size={86}/><div><div className="eyebrow">{t('home.quests.eyebrow')}</div><h2>{t('home.quests.title')}</h2><p>{t('home.quests.body')}</p></div><div className="quest-meters"><button onClick={() => { go('automations'); setExecutionFilter('running'); }}><strong>{jobs.filter(i => i.schedule?.running === true).length}</strong><span>{t('home.quests.running')}</span></button><button onClick={() => { go('automations'); setExecutionFilter('waiting'); }}><strong>{jobs.filter(i => i.schedule?.loaded === true && i.schedule?.running === false).length}</strong><span>{t('home.quests.waiting')}</span></button><button className="quest-attention" onClick={() => { go('automations'); setStateFilter('attention'); }}><strong>{jobs.filter(i => i.status === 'attention').length}</strong><span>{t('home.quests.attention')}</span></button></div><button className="secondary" onClick={() => go('automations')}>{t('home.quests.board')}<ArrowRight size={17}/></button></section>
            <button className="world-map-link" onClick={() => go('map')}><GameIcon name="map" size={66}/><span><strong>{t('home.map.title')}</strong><small>{t('home.map.sub')}</small></span><ArrowRight size={19}/></button>
          </>}
          {['library', 'favorites', 'agents', 'automations'].includes(page) && <>
            <div className={`page-heading catalog-heading ${page}`}><GameIcon name={page === 'agents' ? 'agents' : page === 'automations' ? 'automation' : page === 'favorites' ? 'favorites' : 'collection'} size={84}/><div><div className="eyebrow">{t(`catalog.eyebrow.${page}`)}</div><h1>{title}<span className="heading-count">{page === 'agents' ? agents.length : page === 'automations' ? jobs.length : page === 'favorites' ? savedCount : items.length}</span></h1><p>{t(`catalog.body.${page}`)}</p></div></div>
            {page === 'agents' && <div className="agent-count-note">{runtimeKinds.map(r => <span key={r}>{r} <b>{agents.filter(i => i.runtimes.includes(r)).length}</b></span>)}<small>{t('agents.countNote')}</small></div>}
            {page === 'automations' && <div className="quest-status-note"><Clock3 size={18}/><span>{t('quests.note')}</span></div>}
            {page === 'automations' && <div className="execution-tabs" aria-label={t('quests.executionAria')}>{[['all', t('filter.all')], ['running', t('filter.running')], ['waiting', t('filter.waiting')]].map(([value, label]) => <button key={value} aria-pressed={executionFilter === value} className={executionFilter === value ? 'selected' : ''} onClick={() => setExecutionFilter(value)}>{label}</button>)}</div>}
            <div className="catalog-controls"><SearchField value={query} onChange={setQuery} label={page === 'agents' ? t('search.agents') : page === 'automations' ? t('search.automations') : t('search.gear')} placeholder={page === 'agents' ? t('search.agentsPlaceholder') : page === 'automations' ? t('search.automationsPlaceholder') : t('search.gearPlaceholder')}/>
              {page === 'agents' ? <div className="filter-chips" aria-label={t('filter.agentKindAria')}>{[['all', t('filter.everyone')], ...runtimeKinds.map(r => [r, r])].map(([v, l]) => <button key={v} className={agentRuntime === v ? 'selected' : ''} aria-pressed={agentRuntime === v} onClick={() => setAgentRuntime(v)}>{l}</button>)}<span className="chip-divider"/>{tl('filter.quick').map(w => <button key={w} className={query === w ? 'selected' : ''} aria-pressed={query === w} onClick={() => setQuery(query === w ? '' : w)}>{w}</button>)}</div> : page === 'automations' ? <div className="filter-chips" aria-label={t('filter.jobKindAria')}>{[['all', t('filter.all')], ['calendar', t('filter.calendar')], ['interval', t('filter.interval')], ['resident', t('filter.resident')], ['ondemand', t('filter.ondemand')], ['other', t('filter.other')]].map(([v, l]) => <button key={v} className={jobKind === v ? 'selected' : ''} aria-pressed={jobKind === v} onClick={() => setJobKind(v)}>{l}</button>)}</div> : <div className="filter-chips categories" aria-label={t('filter.categoryAria')}><button className={category === 'all' ? 'selected' : ''} aria-pressed={category === 'all'} onClick={() => setCategory('all')}>{t('filter.all')}</button>{categories.map(c => <button key={c.id} className={category === c.id ? 'selected' : ''} aria-pressed={category === c.id} onClick={() => setCategory(c.id)}>{c.short}<span>{counts[c.id]}</span></button>)}</div>}
              {page !== 'agents' && <div className="filter-selects"><label><span>{t('filter.machine')}</span><select value={machine} onChange={e => setMachine(e.target.value)} aria-label={t('filter.machineAria')}><option value="all">{t('filter.allMachines')}</option>{machines.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}</select></label><label><span>{t('filter.state')}</span><select value={stateFilter} onChange={e => setStateFilter(e.target.value)} aria-label={t('filter.stateAria')}><option value="all">{t('filter.allStates')}</option><option value="observed">{t('status.observed')}</option><option value="configured">{t('status.configured')}</option><option value="attention">{t('status.attention')}</option><option value="unknown">{t('status.unknown')}</option></select></label></div>}
            </div>
            <div className="results-toolbar"><p aria-live="polite"><strong>{filtered.length}</strong> {t('results.count', { n: '' }).trim()}{query && <span> · {query}</span>}</p><div>{(query || category !== 'all' || machine !== 'all' || stateFilter !== 'all' || jobKind !== 'all' || agentRuntime !== 'all' || executionFilter !== 'all') && <button className="text-button" onClick={reset}>{t('results.clear')}<X size={15}/></button>}{page !== 'agents' && <select value={sort} onChange={e => setSort(e.target.value)} aria-label={t('sort.aria')}><option value="default">{page === 'automations' ? t('sort.attentionFirst') : t('sort.default')}</option><option value="name">{t('sort.name')}</option>{page !== 'automations' && <option value="attention">{t('sort.attentionFirst')}</option>}</select>}</div></div>
            {!filtered.length ? <div className="empty-state"><Orbit size={42}/><h2>{page === 'favorites' && !savedCount ? t('empty.favorites.title') : t('empty.title')}</h2><p>{page === 'favorites' && !savedCount ? t('empty.favorites.body') : t('empty.body')}</p><button className="primary" onClick={() => page === 'favorites' && !savedCount ? go('library') : reset()}>{page === 'favorites' && !savedCount ? t('empty.favorites.action') : t('empty.action')}<ArrowRight size={17}/></button></div> : page === 'agents' ? <div className="agent-roster">{filtered.map((i, index) => <AgentCard key={i.id} item={i} index={index} onOpen={() => setSelected(i)} onCopy={() => copy(agentPrompt(i))} saved={favorites.includes(i.id)} onSave={() => favorite(i.id)}/>)}</div> : page === 'automations' ? <div className="list-panel quest-list">{filtered.slice(0, limit).map(i => <JobRow key={i.id} item={i} onOpen={() => setSelected(i)}/>)}</div> : <div className="inventory-grid">{filtered.slice(0, limit).map(i => <ItemRow key={i.id} item={i} onOpen={() => setSelected(i)} saved={favorites.includes(i.id)} onSave={() => favorite(i.id)}/>)}</div>}
            {page !== 'agents' && filtered.length > limit && <div className="load-more"><span>{t('loadMore.count', { shown: Math.min(limit, filtered.length), total: filtered.length })}</span><button className="secondary" onClick={() => setLimit(n => n + 24)}>{t('loadMore')}<ChevronRight size={17}/></button></div>}
          </>}
          {page === 'sources' && <SyncPage inventory={inventory} sync={sync} now={now} error={error} stale={stale} lastContact={lastContact} onRefresh={() => void refresh()}/>}
          {page === 'map' && <><div className="page-heading"><div><div className="eyebrow">{t('map.eyebrow')}</div><h1>{t('map.title')}</h1><p>{t('map.body')}</p></div></div><div className="architecture-flow">{[{ label: t('map.stage.think'), sub: t('map.stage.think.sub'), ids: ['model'], icon: Orbit }, { label: t('map.stage.run'), sub: t('map.stage.run.sub'), ids: ['cli', 'agent'], icon: Sword }, { label: t('map.stage.tools'), sub: t('map.stage.tools.sub'), ids: ['connection', 'skill'], icon: Backpack }, { label: t('map.stage.orchestrate'), sub: t('map.stage.orchestrate.sub'), ids: ['harness', 'automation'], icon: Network }].map((l, index) => <section key={l.label}><span className="map-stage">0{index + 1}</span><GameIcon name={(['guild', 'agents', 'collection', 'automation'] as const)[index]} size={90}/><small>{l.sub}</small><h2>{l.label}</h2><div>{l.ids.map(id => { const c = categoryOf(id as Category); return <button key={id} onClick={() => openCategory(c.id)}><CategoryArtwork category={c.id}/><strong>{c.label}</strong><span>{counts[c.id]}</span><ChevronRight size={16}/></button>; })}</div></section>)}</div><p className="plain-note"><Info size={18}/>{t('map.note')}</p>{items.some(i => i.category === 'harness') && <section className="section-block"><SectionTitle title={t('map.routing')}/><div className="inventory-grid">{items.filter(i => i.category === 'harness').slice(0, 12).map(i => <ItemRow key={i.id} item={i} onOpen={() => setSelected(i)}/>)}</div></section>}</>}
          <footer className="main-footer"><span><GameIcon name="guild" size={24}/> {guildName.toUpperCase()} <i/>{t('footer.private', { player: playerName })}</span><button onClick={() => go('sources')}>{t('footer.sync')}<ChevronRight size={15}/></button></footer>
        </>}
      </main>
    </div>
    <nav className="mobile-nav" aria-label={t('nav.mobileAria')}>{navigation.map(n => <button key={n.id} className={page === n.id ? 'active' : ''} onClick={() => go(n.id)} aria-current={page === n.id ? 'page' : undefined}><GameIcon name={n.art} size={48}/><span>{n.label}</span></button>)}</nav>
    {currentItem && <ItemDetail item={currentItem} items={items} onClose={() => setSelected(null)} onSelect={setSelected} onCopy={copy} onSave={() => favorite(currentItem.id)} saved={favorites.includes(currentItem.id)}/>}
    {searchOpen && <GlobalSearch items={items} onClose={() => setSearchOpen(false)} onSelect={i => { setSearchOpen(false); setSelected(i); }}/>}
    {toast && <div className="toast" role="status"><Check size={19}/>{toast}</div>}
  </div>;
}
function PlayerMini() {
  const [failed, setFailed] = useState(false);
  const avatar = config.player?.avatar;
  return avatar && !failed ? <img className="player-miniature" src={avatar} alt="" width={42} height={42} onError={() => setFailed(true)}/> : <PlayerAvatar size={42} className="player-miniature"/>;
}
function SectionTitle({ title, eyebrow, action, onAction }: { title: string; eyebrow?: string; action?: string; onAction?: () => void }) { return <div className="section-title"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action && <button className="text-button" onClick={onAction}>{action}<ChevronRight size={17}/></button>}</div>; }
function DeviceStatus({ inventory, now, onOpen }: { inventory: Inventory; now: number; onOpen: () => void }) {
  const known = inventory.machines && !Array.isArray(inventory.machines) ? inventory.machines : {};
  return <section className="devices" aria-label={t('devices.aria')} style={{ gridTemplateColumns: `repeat(${Math.min(3, Math.max(1, machines.length))},1fr)` }}>{machines.map(m => { const record = (known[m.id] || {}) as Machine, checked = record.checkedAt, seconds = checked ? (now - Date.parse(checked)) / 1000 : Infinity, unavailable = record.stale === true || record.status === 'unavailable' || record.status === 'unknown' || seconds > (m.kind === 'ssh' ? 300 : 180), Icon = m.kind === 'ssh' ? Laptop : Monitor; return <button key={m.id} onClick={onOpen}><Icon size={20}/><span><strong>{m.label}</strong><small title={date(checked, true)}>{checked ? `${unavailable ? t('device.last') : t('device.checked')} ${ago(checked, now)}` : t('device.none')}</small></span><span className={`device-state ${unavailable ? 'delayed' : 'fresh'}`}><span className="sync-dot"/><span>{unavailable ? t('device.stale') : t('device.fresh')}</span></span><ChevronRight size={15}/></button>; })}</section>;
}
function AgentCard({ item, index, onOpen, onCopy, saved, onSave }: { item: Item; index: number; onOpen: () => void; onCopy: () => void; saved: boolean; onSave: () => void }) { const name = shortName(item); return <article className="agent-card"><div className="agent-card-top"><span className="agent-number">{t('agent.number')} {String(index + 1).padStart(2, '0')}</span><span className="agent-runtime">{(item.runtimes[0] || '').toUpperCase()}</span><button className={`icon-button ${saved ? 'saved' : ''}`} aria-pressed={saved} onClick={onSave} aria-label={saved ? t('fav.remove', { name }) : t('fav.save', { name })}><GameIcon name="favorites" size={26}/></button></div><button className="agent-open" onClick={onOpen} aria-label={t('agent.viewAria', { name })}><DepthSurface className="agent-art"><CharacterPortrait item={item} size={180}/></DepthSurface><span className="agent-class">{roleTitle(item)}</span><h2>{name}</h2><p>{strengths(item).slice(0, 2).join(' · ') || item.summary}</p><span className="agent-view">{t('agent.view')}<ArrowRight size={16}/></span></button><button className="agent-copy" onClick={onCopy} aria-label={t('agent.copyAria', { name })}><Copy size={16}/>{t('agent.copyRequest')}</button></article>; }
function SyncPage({ inventory, sync, now, error, stale, lastContact, onRefresh }: { inventory: Inventory; sync: SyncMeta | null; now: number; error: string; stale: boolean; lastContact: number | null; onRefresh: () => void }) {
  return <><div className="page-heading"><div><h1>{t('syncPage.title')}</h1><p>{t('syncPage.body')}</p></div><button className="secondary" onClick={onRefresh}><RefreshCw size={18}/>{t('syncPage.now')}</button></div>
    <section className="sync-summary"><span className={`sync-indicator ${error || stale ? 'warning' : ''}`}><RefreshCw size={25}/></span><div><h2>{error ? t('syncPage.reconnecting') : stale ? t('syncPage.stale') : t('syncPage.live')}</h2><p>{error || t('syncPage.liveBody')}</p></div></section>
    <DeviceStatus inventory={inventory} now={now} onOpen={onRefresh}/>
    <section className="list-panel sync-facts"><dl className="facts"><div><dt>{t('syncPage.collectorSent')}</dt><dd>{ago(sync?.heartbeatAt, now)}<small>{date(sync?.heartbeatAt, true)}</small></dd></div><div><dt>{t('syncPage.serverReceived')}</dt><dd>{ago(sync?.receivedAt, now)}<small>{date(sync?.receivedAt, true)}</small></dd></div><div><dt>{t('syncPage.screenChecked')}</dt><dd>{lastContact ? ago(new Date(lastContact).toISOString(), now) : t('syncPage.unchecked')}</dd></div><div><dt>{t('syncPage.cadence')}</dt><dd>{t('syncPage.cadenceValue')}<small>{t('syncPage.cadenceDetail')}</small></dd></div><div><dt>{t('syncPage.revision')}</dt><dd>{sync?.revision ?? t('syncPage.notFetched')}</dd></div></dl></section>
    <section className="section-block"><SectionTitle title={t('syncPage.sourcesTitle')}/><div className="list-panel source-list">{inventory.sources.map(source => <div key={source.name}><span><strong>{source.name}</strong><p>{source.scope}</p></span><span><strong>{t('syncPage.sourceItems', { n: source.count })}</strong><time>{date(source.collectedAt, true)}</time></span></div>)}</div><p className="section-note">{t('syncPage.sourcesNote')}</p></section>
    <section className="section-block"><SectionTitle title={t('syncPage.legendTitle')}/><div className="list-panel definition-list">{(['observed', 'configured', 'attention', 'unknown'] as const).map(key => <div key={key}><strong>{t(`syncPage.legend.${key}`)}</strong><p>{t(`syncPage.legend.${key}Body`)}</p></div>)}</div></section>
    <details className="coverage-notes"><summary>{t('syncPage.coverage')}</summary><ul>{inventory.notes.map((note, index) => <li key={index}>{note}</li>)}</ul><p>{t('syncPage.coverageNote')}</p></details>
  </>;
}
function GlobalSearch({ items, onClose, onSelect }: { items: Item[]; onClose: () => void; onSelect: (item: Item) => void }) {
  const [query, setQuery] = useState('');
  const results = items.filter(i => matches(i, query)).slice(0, 15);
  return <Modal label={t('globalSearch.aria')} onClose={onClose}><h2>{t('globalSearch.title')}</h2><SearchField value={query} onChange={setQuery} autoFocus label={t('globalSearch.inputAria')}/><div className="global-search-results">{results.map(i => <button key={i.id} onClick={() => onSelect(i)}><span><strong>{i.name}</strong><small>{i.summary}</small></span><ChevronRight size={18}/></button>)}{results.length === 0 && <p className="empty-state">{t('globalSearch.empty')}</p>}</div></Modal>;
}
applyTheme();
createRoot(document.getElementById('root')!).render(<CharacterProvider><App/></CharacterProvider>);
